--Always add health_info
WHITE_FILTER = {wilson=true, catcoon=true, monkey=true, pumpkin_lantern=true, chester=true, spiderden_2=true, spat=true, maxwellendgame=true, mole=true, eyeturret=true, glommer=true, mossling=true, spider_warrior=true, walrus=true, mosquito=true, minotaur=true, deerclops=true, waxwell=true, ruins_rubble_vase=true, wolfgang=true, dragonfly=true, wasphive=true, frog=true, moose=true, ruins_rubble_chair=true, lavae=true, shadowtentacle=true, bishop_nightmare=true, slurper=true, smallbird=true, merm=true, spiderhole=true, snurtle=true, bishop=true, penguin=true, dropperweb=true, tentacle_pillar_arm=true, pigguard=true, abigail=true, tallbird=true, ruins_chipbowl=true, wx78=true, pigman=true, butterfly=true, rook=true,
 ruins_plate=true, leif=true, shadowwaxwell=true, bearger=true, spider_dropper=true, balloon=true, koalefant_summer=true, teenbird=true, ruins_bowl=true, ruins_chair=true, spiderqueen=true, spider_spitter=true, slurtlehole=true, ruins_table=true, wendy=true, koalefant_winter=true, crow=true, spiderden=true, wickerbottom=true, terrorbeak=true, spider_hider=true, spiderden_3=true, bernie_active=true, bat=true, crawlingnightmare=true,
 wall_moonrock=true, ufo=true, ruins_vase=true, wathgrithr=true, tentacle=true, wall_stone=true, babybeefalo=true, birchnutdrake=true, spider=true, bee=true, robin_winter=true, wall_wood=true, beehive=true, eyeplant=true, hound=true, houndmound=true, firehound=true, buzzard=true, robin=true, wes=true, lightninggoat=true, worm=true, webber=true, willow=true, slurtle=true, knight=true, nightmarebeak=true, rocky=true, killerbee=true,
 little_walrus=true, woodie=true, ruins_rubble_table=true, rook_nightmare=true, beefalo=true, mandrake_active=true, ghost=true, krampus=true, warg=true, icehound=true, wall_hay=true, lavae_pet=true, lureplant=true, bunnyman=true, perd=true, rabbit=true, tentacle_pillar=true, crawlinghorror=true, leif_sparse=true, wall_ruins=true, dummytarget=true, knight_nightmare=true,

personal_chester=true, robye=true, robgr=true, ntpie=true, ghosthound2=true, tucan=true, bluer=true, personal_dogoo=true, 
sickv=true, mech_stone=true, akuaku=true, ghosthound=true, summonclone=true, bluechester=true, baby_koalefant_summer=true, 
shadowmusha=true, bulbo=true, partychester=true, afester=true, bigdaddy=true, summonassassin=true, baby_koalefant_winter=true, 
summonskip=true, glimmer=true, summontibber=true, summonkyoko=true, ewelo=true, locked_mech_stone=true, wall_tungsten=true, 
babbyglimmer=true, babbyglommer=true, saberwild=true, terrorbeakpet=true, tentacle_frost=true, agorian=true, summonbeserker=true, 
stafflight3=true, sentinel=true, arong_baby=true, mech_wood=true, koalefant_forest=true, dondoydoy=true, mech_moonrock=true, 
brownspider_hole=true, redspider_hole=true, bluespider_hole=true, greenspider_hole=true, summonrhino=true, ws_03=true, 
summonchop=true, dst_balloon2=true, mech_ruins=true, wormspider=true, ghost2=true, mech_hay=true, locked_mech_moonrock=true, 
bunshin=true, locked_mech_ruins=true, dst_ghost2=true, koalefant_feathered=true, balloon2=true, beargerguardian=true, 
steve=true, sj_bearger=true, deerclopsguardian=true, koalefant_frost=true, redspider=true, sakura_ghost=true, brownspider=true, 
heavysentry=true, bluespider=true, seasonalpenguin=true, greenspider=true, sj_deerclops=true, koko=true, wargguardian=true, 
spiderqueenguardian=true, wargpup=true, wall_stone_extended=true, sj_moose=true, worm_spiderling=true, drone=true, worm_rocky=true, 
goblin=true, webzterden=true, gcatcoon=true, darkwolfgang=true, sj_dragonfly=true, darkwes=true, zergling=true, koalefant_rocky=true, 
darkwebber=true, darkwaxwell=true, darkwicker=true, tentacle_garden=true, stingerturret=true, darkwillow=true, darkspider=true, 
licking=true, lana=true, attyla=true, darkzoro=true, iso_licking=true, dhz_invisible=true, darkluffy=true, darkace=true, darkwoodie=true, 
overlord=true, ship=true, darkwilson=true, darkwendy=true, worm_fighter=true, wall_bone=true, darkwigfrid=true, darkotter=true, 
darkwx78=true, tpg_licking=true, worm_flying=true, darkturkey=true, darkdaimeng=true, darksanji=true, ukauka=true, darkabigail=true, 
darkbishop=true, darklaw=true, worm_warrior=true, huliclone=true, roncatdoll_katia=true, schizo_friend=true, wall_ruins_extended=true, 
pipe=true, grasshopper=true, wall_pomarble=true, worm_assassin=true, roncatdoll=true, luneoid=true, ws_05=true, fidget=true, warhound=true, 
crawlingbuddy=true, terrorfriend=true, wonkyskeleton=true, spartan808=true, tai=true, nadiashead=true, hydralisk=true, koalefant_albino=true, 
ws_02=true, licking_helper=true, tecolin_chester=true, depthdwellerqueen=true, servbots=true, wall_moonrock_extended=true, icebee=true, 
madoka=true, wall_hay_extended=true, wall_wood_extended=true, drophyd=true, ws_04=true, googleirl=true, koalefant_nightmare=true, miho=true, 
skitemtrouppleorb=true, maci=true, elphelt=true, ai=true, jao=true, xadrez=true, faroz=true, hella=true, ace=true, plutia=true, zoro=true, zg_mo_icearcher=true, 
ivan=true, zg_ch_wicker=true, zg_mo_perd=true, catcoon=true, darktuxingsun=true, woodie=true, saitama=true, zg_ch_wilson=true, zg_ch_willow=true, 
zg_mo_abigail=true, zg_ch_wendy=true, zg_ch_wolfgang=true, zg_mo_firegirl=true, zg_ch_wx78=true,

moonnutdrake2=true, zg_mo_tentacle=true, moonnutdrake=true, summonshelly=true, summonjill=true, ichthy=true, mrdemon=true, 
zg_mo_hound=true, zg_ch0_soldier00=true, webbiterden=true, zg_mo_icehound=true, pigking=true, dragoon=true, zg_mo_firehound=true, 
zg_it_balloon=true, musha=true, webzerden=true, tamamo=true, olaf=true, warly=true, kiwi=true, bee_h=true, bkbarb=true, tong_leo=true, 
butterfly0=true, warfbug=true, saitamatwo=true, skeleton_living=true, madnut=true, frog0=true, sans=true, denmother=true, white=true, 
naruto=true, freki=true, supportoise=true, esctemplate=true, toad=true, reaper=true, wodnik=true, wall_asia=true, rainbowhound=true, frisk=true, 
snapper=true, xenomorph=true, woo=true, sheat=true, wuby=true, saberlion=true, thegreatpapyrus=true, who=true, zg_mo_skelarcher=true, wigfridhead=true, 
ewecusguardian=true, ewecuslamb=true, zg_ch_webber=true, zg_mo_skel=true, ironman=true, ligeia=true, san=true, rin=true, edgar=true, reimu=true, 
twigs_birchnutdrake=true, zg_mo_frog=true, babyspat=true, wilton=true, devon=true, yoda=true, yurixa=true, zg_mo_evergreen=true, zinnia=true, 
sanji=true, zg_mo_snowwolf=true, walani=true, remonkey=true, xcho=true, hanzo=true, spiderspitterqueen=true, sophie=true, wray=true, darkwolfgangghost=true, 
zg_mo_butterfly=true, ear=true, kiwiboss=true, dib=true, zg_mo_stygiandoll=true, watthew=true, zim=true, darkiplier=true, pigmanplayer=true, 
tsoma=true, sonic=true, zg_mo_skel1=true, morgue=true, nightmareplayer=true, pluto=true, zg_mo_spider=true, zg_mo_skel0=true, kyoko=true, 
darkwendyghost=true, redpig_bearger=true, chopper=true, willrick=true, broccoli=true, shadowpuppet=true, flameguin=true, gnar=true, wayland=true, 
hounddarkplayer=true, markiplier=true, brs=true, summonkurumi=true, sakura=true, redpig_pigman=true, sollyz=true, darkwoodieghost=true, 
zg_mo_shadow=true, zg_ch_waxwell=true, zg_mo_blackwolf=true, zg_ch_woodie=true, zg_mo_beaver=true, zg_ch_wigfrid=true, zg_ch_wes=true, 
zg_mo_wolf=true, luffy=true, homura=true, darkwigfridghost=true, raven=true, illya=true, aikawa=true, deadpool=true, zg_mo_skel2=true, zg_mo_skel3=true, 
metro=true, whandler=true, genos=true, daniel=true, mettaton=true, shelldummy=true, wyvard=true, annie=true, elli=true, koalefant_frost_base=true, 
solaire=true, zg_ch1_ace=true, vader=true, bigby=true, kylo=true, chara=true,
shadowfran=true, hector_chester=true, arcticopteryx=true,
olaf_c=true, shw=true, wall_mud=true, wynn=true, sharkitten=true, aria=true, haruz=true, voltoad=true,  
fran=true, deer=true, angel=true, hastur=true, shiki=true, mitsuru=true, crashbandi=true, medic=true, wortox=true, yasuo=true, s115=true, 
tigershark=true, gilbo=true, m_lightninggoat=true, pigred=true, slurperp=true, walter=true, wukong=true, grom=true, grell=true, tallbirdplayer=true, 
geralt=true, rocklobsterp=true, cavester=true, xcal_p=true, freebre=true, caster=true, guardianp=true, horo=true, bearplayer=true, huli=true, 
asuna=true, houndiceplayer=true, deerplayer=true, maggotplayer=true, mokou=true, gluttony=true, womp=true, greenchocobo=true, luigi=true, 
mermplayer=true, undyne=true, pyro=true, shadow__hound=true, wqueenspiderplayer=true, ni=true, lilum=true, tirix=true, cspiderp=true, wilbur=true, 
bunnyp=true, wormp=true, kyle=true, soldier=true, wapiti=true, dragonplayer=true, bm=true, moosegooseplayer=true, shadow2player=true, cipher=true, 
monkeyp=true, ghostplayer=true, cspider2p=true, law=true, imp=true, batp=true, darkwickerghost=true, walrusplayer=true, babygooseplayer=true, 
gir=true, blueplushound=true, queenspiderplayer=true, sasuke=true, blackspiderplayer=true, castiel=true, heavy=true, catplayer=true, houndplayer=true, 
link=true, darkdaimeng2=true, gbe=true, momiji=true, skirt=true, beefplayer=true, redplushound=true, vargplayer=true,

hutch=true, tentacle_shadow=true, summonaron=true, scout=true, edward=true, jack=true, bamami=true, jinx=true, usopp=true, sdabigail=true, 
darkwx78ghost=true, buker=true, ruk=true, arc=true, wurp=true, guts=true, saphira=true, alduin=true, raiku=true, energyfennec=true, tuxingsun=true, 
warren=true, woodlegs=true, kasen=true,

grassgekko=true, shadowlumber=true, shadowminer=true, stickybomb=true, shadowduelist=true, shadowdigger=true, 
stickybomb_crit=true, summonjarvi=true, phoebe=true, mag=true, waxwing=true, hoopoe=true, mrdemon2=true, pennyduelist=true, 
gate_of_babylon=true, ninjaclone=true, summonminichop=true, demoman=true, spidey=true, kutsil=true, kuriboh=true, gaster=true, 
archer=true, saber=true, greatsage=true, jeff=true, default=true, noodle=true, happy=true, madeleine=true, teemo=true, mortox=true, 
charlie=true, ker=true, pryce=true, spiderman=true, barczak=true, elizabeth=true, kotori=true, mario=true, asriel=true, twister=true, 
finnthehuman=true, unik=true, twister_seal=true, zg_fx_luffyarm=true, revok=true, animsparrow=true, spy=true, hk=true, tf2soldier=true, 
poisson_yarn=true, wooly=true, wiltonmod=true, devildog=true, shapeshifter=true, neptune=true, nasking=true, zacharie=true, ma=true, penny=true, 
treeplayer=true, perfect=true, spooky1=true, thomas=true, moth=true, digiduelist=true, anub=true, neopolitan=true, lawrence=true, spek=true, 
chamber=true, esentry=true, death=true, growlie=true, spooky2=true, smallbirdp=true, scootaloo=true, jtr=true, morewords=true, spooky4=true, 
mystery=true, clockwork3player=true, ada=true, malami=true, toadstool=true, linos=true, frits_ghost=true, digilumber=true, blanc=true, dispenser=true, 
rakky=true, tower=true, evil_mound=true, digiminer=true, wishes=true, bruterobot=true, poisonspiderden=true, digidigger=true, cain=true, super_reaperrobot=true, 
yang=true, houndredplayer=true, reaperrobot=true, warriorp=true, north=true, draugr=true, hinagiku=true, vegeta_evil=true, clockwork1player=true, 
summerfly=true, effie=true, refletfe=true, krampusp=true, donaldtrump=true, danka=true, eli=true, snicketytom=true, terrorist=true, wayrra=true, 
flash=true, muffet=true, brook=true, rubi=true, lucario=true, chimarrao=true, teto=true, webbiter=true, evilbutterfly=true, saibamen=true, yuno=true, 
reflet=true, snc=true, biker=true, sealfollower=true, baleog=true, caitlin=true, clockwork2player=true, spooky3=true, whitespiderplayer=true, 
knight_nightmare=true, celnar=true, bluebird=true, rei=true, alphys=true, nedelya=true, spooky=true, chillywilly=true, dante=true, elecman=true, 
fiddlesticks=true, gollum=true,

zg_spider_steel=true, shadowtentacle2=true, offghost=true, clockqueen=true, scythe=true, marisa=true, denguard=true, 
doge=true, barbarianking=true, iceking=true, miko=true, firespider=true, asp_ghost=true, kokoflame=true, kokocrazy=true, kokofrost=true, 
fuzzy=true, miku=true, kokoshiny=true, micky=true, kagerou=true, reisen=true, koor=true, doflamingo=true, hev=true, twigs_character=true, 
sharkittenp=true, weeseeks=true, kokocadence=true, winston=true, tenshi=true, chesterp=true, wakkari=true, mutt=true, elephantplayer=true, 
tina=true, watcher=true, glommerp=true, thejudge=true, grull=true, plaguedoc=true, grassgek=true, gaobee=true, wulfe=true, mokey=true, tigersharkp=true, 
xion=true, flyp=true, rg01=true, amateratsu=true, twisterp=true, tula=true, snakep=true, isaac=true, alice=true, nue=true, lrj=true, samansha=true, 
widgette=true, jesse=true, riolu=true, tentacle2=true, bav=true, kokoguard=true, stikmen=true, poisonspider=true, gekkop=true, dragoonp=true, 
cc_barbarian=true, ghost2p=true, wogmaw=true, frogp=true, summonsk=true, kokodiseased=true, yuuka=true, mahd=true, haunter=true, shadowplayer=true, 
weiss=true, tgb=true, zobbit=true, roncat=true, genesis=true, beep=true, dipper=true, mikasaackerman=true, queenelsa=true, vaultboy=true, shadowwilson=true, 
jon=true, tzgn=true, king_piccolo=true, mutated_namek=true, kuroneko=true, no=true, perdp=true, molep=true, wuppet=true, olivia=true, cinnamon_active=true, 
blackchocobo=true, potato=true, yellowchocobo=true, swwarriorp=true, merm2p=true, pengullp=true, redchocobo=true, summonsaber=true, oprobin=true, 
crykov=true, clyde=true, jormungandr=true, oxp=true, noz=true, riktor=true, stinkrayp=true, fox=true, wisp=true, wynter=true, drei=true, palmtreep=true, 
hogp=true, magyaku=true, fly2p=true, doydoyp=true, wei=true,

greenworm=true, personal_licking=true, summonfran=true, snake=true, snake_poison=true, pigman_yellow=true, suofeiya_fenshen=true, 
hatbunnyman=true, yoshino_rabbit=true, wildbeaver=true, colored_bunnyman=true, rabbit_snow=true, yeti=true, perma_grassgekko=true, 
pigman_blue=true, wolliedog=true, leif_snow=true, pigman_gray=true, wildbore=true, ox=true, perma_beardlord=true, 
reingoat=true, perma_mosquito=true, assasin_wilson=true, canary=true, kurumi_self=true, giant_bunnyman=true, varg=true, 
goddess_spider_hostile=true, houndmound_p=true, quickiebomb=true, moonhound=true, moonpig=true, spidernest_p=true, 
shadowduelist3=true, loon=true, mutant_bunnyman=true, kb_shadowtentacle=true, goddess_butterfly=true, quickiebomb_crit=true, 
inori=true, greengrassgekko=true, frog_purple=true, pigman_cyborg=true, shadowduelist2=true, spider_poisonous=true, 
tieravil=true, grey_lightning_goat=true, merm_blue=true, treeguard=true, tinypig=true, bishop_guard=true, goddess_spider=true, 
weqb=true, akatsuki=true, bearger_friend=true, jango=true, shiranui=true, gardevoir=true, goddess_statue=true, 
hitsugaya=true, pokemon=true, fancy_penguin=true, hibiki=true, ram=true, clownpiece=true, gaohive=true, inazuma=true, 
jugger=true, scarvolo=true, lapis=true, rem=true, doctorcrane=true, babyox=true, hououin=true, mea=true, ikazuchi=true, 
electrichound=true, over9000=true, yoshino=true, wanda=true, alluringskull=true, ruby=true, shadowdeerclops=true, 
rabbitp=true, shinycario=true, summonspooky=true, pao=true, rg02=true, spidernest2_p=true, spidernest3_p=true, 
webzer=true, musha_small_rep=true, tohsaka=true, peri=true, meru=true, flupp=true, zg_ch2_mihawk=true, darkdexter=true, 
void=true, neferpitou=true, io=true, goddess_sword=true, crabbitp=true, apep=true, houndvenomp=true, pearl=true, 
darkhound=true, icedexter=true, chen=true, telehound=true, wabbit=true, smalldoydoyp=true, destroyerhound=true, 
packp=true, constantine=true, lyrica=true, cirno=true, slurtlep=true, charliethegardener=true, toriel=true, bob=true, 
melon=true, tewi=true, loyalcat=true, pit=true, biohound=true, serenaanipoke=true, walker=true, izayoi=true, goatp=true,

dyc_door_stone=true, dyc_wall_stone=true, dyc_door_limestone=true, dyc_door_wood=true, fence_gate=true, dyc_wall_limestone=true, 
dyc_door_hay=true, fence=true, dyc_wall_wood=true, dyc_door_ruin=true, dyc_wall_hay=true, dyc_door_moonrock=true, 
dyc_wall_ruin=true, dyc_wall_moonrock=true, beeguard=true, beequeen=true, remibat=true, shadow_knight=true, shadow_bishop=true, 
shadow_rook=true, canary_poisoned=true, musha_spore_fire=true, skeletonguard=true, icebeefalo=true, beefaloking=true, 
spiderhole_p=true, fireward=true, zg_ch2_wathgrithr=true, zg_ch2_wolfgang_mighty=true, zg_ch2_wx78=true, zg_ch2_woodie=true, 
zg_ch2_waxwell=true, zg_ch2_wendy=true, zg_ch2_wes=true, zg_ch2_wilson=true, zg_ch2_wickerbottom=true, zg_ch2_webber=true, 
zg_ch2_willow=true, zg_fx_balloon=true, firebeefalo=true, lightningbeefalo=true, engineer=true, summonmana=true, 
kyoku=true, hqg=true, fenghoho=true, yohime=true, fhl=true, kurumi=true, shovelknight=true, shinai=true, rikka=true, 
fairies=true, sentinel_bishop=true, sentinel_knight=true, remilia=true, luoxiaofei=true, batter=true, sulili=true, 
darkimp=true, frog_a=true, winnie=true, hadabra=true, pkc_longpig=true, pkc_cuipig=true, infernalboss=true, cheese=true, 
pkc_redpig=true, kokocarrier=true, pkc_bigpig=true, shadow_knightp=true, prophet=true, zgsabber=true, obenja=true, 
freyja=true, lucas=true, pixie=true, gggroot=true, lucina=true, poly=true, glace=true, shenxiustone=true, daryl=true, 
rivendst=true, shenxiuclone=true, mana_moose=true, mana_deerclops=true, mana_bearger=true, sand__priest=true, mabel=true, 
error_sans=true, dwillow=true, cream=true, mana_dragonfly=true, idf=true, asparagus=true, stagehandp=true, monkey__king=true, 
feliciaday=true, pig__sy=true, tang__seng=true, white__dragon__horse=true, thana=true, suofeiya=true, pennywise=true, 
ratchet=true, tazdor=true, winged=true, toadstoolp=true, wiley=true, shrek=true, koalefant_albino_base=true, vergence=true, 
eddiebox=true, nalf=true, webber_frog=true, wilmore_turret=true, ori=true, astrid=true, ink_sans=true, capamerica=true, 
athena=true, jason=true, webster=true, shadow_rookp=true, shikieiki=true, wolft=true, neon=true, dragon=true, dutyexoai=true, 
warper=true, superwilson=true, shadow_bishopp=true, nicole=true, withers=true, lola=true, hutchp=true, hon=true,

dyc_fence_gate=true, dyc_fence=true, klaus=true, deer_blue=true, deer_red=true, shadowbatenemy=true, td1madaogolbalmengxin=true, 
wln=true, wall_living=true, wall_hedge=true, shadowbatminion=true, wall_reed=true, abigail_festive=true, balloon_festive=true, 
spiderden_festive=true, spider_snowman=true, lwww=true, royalspiderqueen=true, pkc_eyeturret_big=true, pkc_eyeturret_red=true, 
pkc_pigman_big=true, pkc_pigman_red=true, pkc_eyeturret_long=true, pkc_pigman_long=true, iceclops=true, vargpup=true, 
pkc_eyeturret_cui=true, pkc_pigman_cui=true, mamavarg=true, honeybearger=true, spider_warrior_ice=true, eyeturret_diamond=true, 
bomballoon=true, wisspher=true, littlesnot=true, bigsnot=true, chris=true, draw_ghost=true, wallander=true, sanity_ghost=true, 
tails=true, nelke=true, newpig=true, will=true, sheele=true, fei=true, rhunari=true, xq=true, sdf=true, beequeenp=true, 
cuckoo=true, alucard=true, klausp=true, wolfiedog=true, trainerred=true, babyhoundp=true, jones=true, pikachu=true, 
blake=true, heather=true, dragonfly=true, peridot=true, stw=true, selene=true, nefarious=true, walden=true, widow=true, 
xiana=true, aya=true, birdp=true, birchnutterp=true, grillby=true, mlucario=true,

--2019
antlion=true, bernie_big=true, boat=true, 
canary=true, carrat=true, clayhound=true, crawlinghorror=true, crawlingnightmare=true, 
fence=true, fence_gate=true, fruitdragon=true, 
moonbutterfly=true, mutated_penguin=true, mutatedhound=true, nightmarebeak=true, 
pigelite1=true, pigelite2=true, pigelite3=true, pigelite4=true, puffin=true, quagmire_park_gate=true, 
quagmire_pigeon=true, sandblock=true, sandspike=true, shadowchanneler=true, shadowdigger=true, 
shadowduelist=true, shadowlumber=true, shadowminer=true, spider_moon=true, stalker=true, stalker_atrium=true, stalker_forest=true, 
terrorbeak=true, toadstool_dark=true, winona_catapult=true, 

--2019/10
cookiecutter=true, fake_target_death=true, dyc_park_fence=true, dyc_park_gate=true, boat_small=true, sandspike_med=true,
sandspike_short=true, sandspike_tall=true, sa_deer=true, debris_campfire=true, debris_plank=true, debris_cookpot=true,
dyc_wall_pigruin=true, chest_monster=true, boltwingout_shuck=true, fruitbat=true, tadalin_tower=true, mean_flytrap=true,
adult_flytrap=true, carney=true, moonnutdrake_lamb=true, pog=true, boat_large=true, boat_giant=true, homura_detonator=true,
stalker_minion2=true, critter_glomling=true, icey_shadow2=true, raindonate=true, stalker_minion1=true, debris_potted_fern=true,
doydoy=true, rainbowjellyfish_planted=true, jellyfish_planted=true, ballphin=true, solofish=true, swordfish=true,
kiana_kaslana_td1madao_broken_poisonous_spider_armor_creature=true, dyc_door_pigruin=true, wall_ice=true, icey_tower=true,
redbarrel=true, elephantcactus_active=true, knightboat=true, tigersharktorch=true, kiana_kaslana_td1madao=true,
wildboreking=true, pigman_royalguard=true, pigman_mechanic=true, pigman_banker=true, pigman_hunter_shopkeep=true,
pigman_collector=true, quagmire_swampig=true, pigman_hunter=true, pigman_usher=true, antqueen=true, pigman_professor=true,
pigman_florist=true, pigman_erudite=true, pigman_beautician=true, pigman_hatmaker=true, pigman_storeowner=true,
antman=true, antman_warrior=true, pigman_collector_shopkeep=true, pigman_farmer=true, pigman_storeowner_shopkeep=true,
pigman_queen=true, mandrakeman=true, pigman_banker_shopkeep=true, pigman_beautician_shopkeep=true, pigman_mechanic_shopkeep=true,
pigman_florist_shopkeep=true, pigman_professor_shopkeep=true, pigman_erudite_shopkeep=true, pigman_mayor_shopkeep=true,
pigman_hatmaker_shopkeep=true, icey_park_fence_short=true, icey_park_fence_tall=true, jade=true, lobster=true,
crab=true, critter_kitten=true, pig_ruins_spear_trap=true, pigeon=true, flup=true, toucan=true, rookwater=true,
slipstor=true, whale_blue=true, firetwister=true, parrot=true, bishopwater=true, divinetree=true, stungray=true,
whale_white=true, kraken=true, quagmire_beefalo=true, cormorant=true, piko=true, grabbing_vine=true, quagmire_pebblecrab=true,
spider_monkey=true, snake_amphibious=true, scorpion=true, icey_park_gate=true, watermelon_catapult=true, bunny19c=true,
elecarmet=true, spider_higher=true, yorha2b_dst_td1madao_mengxin=true, butterfly_tropical=true, p0sty=true, spider_xianfeng=true,
dyc_door_ice=true, spider_haojie=true, yorha2b_dst_td1madao_my_target=true, pigman_infected=true, wormwood=true,
peagawk=true, winona=true, boat_raft=true, mutantkillerbee=true, deidara2_dst_td1madao_explosive_clay_spider=true,
boat_row=true, boat_cargo=true, spider_dragoon=true, mutantparasitebee=true, oldfish_manypeople_player5=true, mutantbee=true,
icey=true, laozi=true, sora=true, deidara2_dst_td1madao_mengxin=true, fence_shyerry=true, goddess_rabbit=true,
soulwendy=true, claywarg=true, mutantbeehive=true, scpzombie=true, dyc_park_door=true, dyc_wall_hedge_layered=true,
dyc_door_hedge_layered=true, spider_bomb=true, pugalisk_segment=true, oldfish_manypeople_player2=true, dollminer=true,
mosquito_poison=true, hoodini=true, dollattackerlance=true, spider_tropical=true, photon_cannon=true, dollbackpacker=true,
jellyfish=true, seagull=true, mermfisher=true, mimic=true, boat_lograft=true, shiro=true, pigguard_minion=true,
imba_kiana_td1madao_broken_poisonous_spider_armor_creature=true, wall_limestone=true, pigman_minion=true, livechest=true,
willow_infected=true, spider_chaser=true, ghost_ai=true, wickerbottom_infected=true, parrot_pirate=true, doydoybaby=true,
primeape=true, puppet_brother=true, seagullwater=true, seele=true, wharang=true, battle19c=true, critter_dragonling=true,
critter_puppy=true, stovester=true, homura_1=true, winona_infected=true, homura_bomb_flash=true, waxwell_infected=true,
wes_infected=true, wathgrithr_infected=true, wendy_infected=true, webber_infected=true, wx78_infected=true, woodie_infected=true,
wolfgang_infected=true, wilson_infected=true, quanyecha=true,

--2019/12
gingerbreadpig=true, squid=true, gingerbreadwarg=true, dyc_wall_hedge_cone=true, mermguard=true, dyc_wall_hedge_block=true,
dyc_door_hedge_cone=true, mermking=true, thunderbird=true, pangolden=true, kingfisher=true, toucan_hamlet=true,
tz_nightmare1=true, parrot_blue=true, dungbeetle=true, tz_nightmare2=true, glowfly=true, wurt=true, gnat=true,
ghosthound3=true, weevole=true, rabid_beetle=true, gingerdeadpig=true, ro_bin=true, cherryling=true, malbatross=true,
gnarwail=true, cropgnat=true, zeta=true, dyc_door_hedge_block=true, banhua_fireelemental=true, giantgrub=true,
scarlia_ghost=true, cropgnat_infester=true, catbird=true, cherry_dragonfly=true, cherry_bee=true, glowfly_cocoon=true,
leshahound=true, hippopotamoose=true, octopus=true, red_lycoris_td1madao_chester_1=true, cherry_beehive=true, chaffinch=true,
frog_traveler=true, boarmound=true, oxbaby=true, swimminghorror=true, boatmetal=true, lafy=true, abigail_human=true,
dollattackerrazor=true, giao2=true, sandspike_med_legion=true, boat_encrusted=true, sandspike_tall_legion=true,
pigman_miner=true, crocodog=true, sandspike_short_legion=true, houndmound_fire=true, fruitdragonfly=true, frog_poison=true,
houndmound_slimey=true, yuanzi=true, pigelitefighter3=true, wanawanatiki=true, goldbishop=true, pigman_royalguard_3=true,
pigelitefighter1=true, dolllumber=true, sona_etwahl=true, boat_armoured=true, pugalisk=true, spider_ape=true, dollattacker=true,
pugalisk_body=true, gnarwail_attack_horn=true, bone_pet=true, pugalisk_tail=true, antman_warrior_egg=true, skill_2_fx=true,
sharx=true, alice_th=true, white_bone=true, hound_slimey=true, sona=true, apple=true, zeb=true, riven2_dst_td1madao_mengxin=true,
poisoncrocodog=true, nohatty_piggy_tfc=true, neza=true, pigelitefighter4=true, kelpy=true, dolldigger=true, koishi=true,
rock_basaltp=true, warfarin=true, merm1=true, critter_perdling=true, pigelitefighter2=true, trapslug=true, packim=true,
ghost_fili=true, ds_knight=true, essar=true, monkey_king=true, snapdragon=true, pidgeonp=true, beetletaurp=true,
ike=true, lograft=true, peekhen=true, pig_royalguard_rich_2=true, pig_royalguard_rich=true, tikiman=true, pigman_royalguard_2=true,
golem=true, frog_poison2=true, wyrd=true, genji=true, ancient_hulk=true, ancient_herald=true, slip=true, merm2=true,
pirateghost=true, battlestandard_shield=true, pugaliskp_body=true, shadowchannelerp=true, saxton=true, starfire=true,
gril=true, ds_cleric=true, yoshi=true, mysteryguard=true, thief_ds=true, sandbagsmall=true, koli=true, illya_mahoo=true,
pugaliskp_tail=true, ezreal_dst_td1madao=true, des_water_snake=true, followerdoll=true, pitpig=true, snortoise=true,
shadow_deerclops=true, shadowtentacle_root=true, goldmonkey=true, gw_frostobstacle=true,

--2021/09
crabking=true, waterplant=true, wall_stone_2=true, wall_ruins_2=true, archive_centipede_husk=true, lightflier=true,
molebat=true, mushgnome=true, dustmoth=true, oceanvine_cocoon=true, friendlyfruitfly=true, archive_centipede=true,
wobster_sheller_land=true, bear=true, billsnow=true, shark=true, spider_healer=true, mk_phantom=true, fruitfly=true,
wall_pig_ruins=true, grassgator=true, ivy_snare=true, boat_raft_rot=true, giantsnow=true, pigman_witch=true, blackcatcoon=true,
ice_deer=true, mammoth=true, myth_redlantern=true, lordfruitfly=true, pigghost=true, quagmiregoat=true, bird_mutant=true,
mermfisherpirate=true, bird_mutant_spitter=true, blackbear=true, snowgoat=true, snowwarg=true, clam=true, wh_frog=true,
oceanhorror=true, laozi_qingniu=true, snowbeetle=true, wobster_moonglass_land=true, mermkingunderwater=true, chicken=true,
ballphin2=true, skyhound=true, reef_jellyfish=true, krakenunderwater=true, myth_goldfrog=true, myth_small_goldfrog=true,
crabking_claw=true, gnarwailunderwater=true, vampirebat=true, gestalt_guard=true, balloonspeed=true, rhino3_yellow=true,
rhino3_blue=true, myth_siving_boss=true, rhino3_red=true, wh_mandrakeman=true, pigbandit=true, balloonparty=true,
dyc_wall_ice=true, yangjian=true, myth_fence=true, summerwalrus=true, dogfish_under=true, paper=true, bramble_core=true,
bramblespike=true, jellyfish_underwater=true, boat_lilypad_medium=true, boat_lilypad_large=true, boat_lilypad_small=true,
panda=true, paper_pifu=true, balloonvest=true, fish5_alive=true, commonfish=true, fish_coi=true, quagmire_salmom_alive=true,
fish2_alive=true, fish4_alive=true, fish3_alive=true, balloonhat=true, moonstorm_static=true, boat_bridge=true,
spider_water=true, lobsterunderwater=true, stungrayunderwater=true, sea_eel=true, shrimp=true, skyhound_warg=true,
homura_bomb_bomb=true, kraken_tentacle=true, pigsy=true, boat_rectangle=true, rainbowjellyfish_underwater=true,
webbedcreature=true, alterguardian_phase2=true, antman2=true, alterguardian_phase3=true, huahua=true, alterguardian_phase1=true,
raft=true, pig_eskimo=true, mermfisherguardunderwater=true, boat_caravel=true, pigking_pigguard=true, squidunderwater=true,
bill=true, koalebeef_summer=true, kraken_jellyfish=true, butterfly_dark=true, wh_pumpkinspider=true, skeletonwarrior=true,
skeletonmage=true, nightmarebeak2=true, ninomae_takodachi=true, skeletonservant=true, myth_yutu=true, spider_snow2=true,
wall_legacy_moonrock=true, lizardman=true, igu_con=true, dyc_door_sea=true, turt_con=true, croc_con=true, sal_con=true,
wall_legacyruins=true, kyno_elephantcactus_active=true, kyno_dragoon=true, wragonfly=true, ge_goatmum=true, ge_trader_merm2=true,
ge_trader_merm=true, homura_bomb_fire=true, greententacle=true, spider_trapdoor=true, kyno_vine1=true, kyno_vine3=true,
kyno_vine2=true, jungletreeguard=true, green_snake=true, amiya=true, critter_lamb=true, nanachi=true, boat_zuida_xing=true,
um_bear_trap_old=true, dyc_wall_sea=true, wall_enforcedlimestone_land=true, hollow_knight=true, mutantassassinhive=true,
mutantdefenderhive=true, kyno_seal=true, kyno_sharkitten=true, cherry_butterfly=true, crawlingnightmare2=true,
koalebeef_winter=true, kyno_peekhen=true, whale_bluefinal=true, bushcrab=true, boat_xiao_xing=true, ge_trader_goatkid=true,
ydj_dst_td1madao=true, ninomae=true, wall_enforcedlimestone=true, dreadeye=true, watercrocodog=true, aphid=true,
woose=true, ge_swamppig_elder=true, critter_lunarmothling=true, uncompromising_rat=true, glutto=true, chogath=true,
windy=true, ge_swamppig=true, peagawk_prism=true, weerclops=true, aip_mud_crab=true, woodlegs1=true, tiddletree=true,
icebearger=true, shadowtroop=true, taiyangta=true, boat_plant=true, gura=true, oikawa=true, nuko=true, lavae_wragonfly=true,
yuki=true, flytrap=true, quagmire_chicken=true, creepingfear=true, slimechunk=true, bishopwaterfixo=true, rookwaterfixo=true,
mami=true, snowmong=true, icedeerclops=true, mutantrangerhive=true, dragonfly_ds=true, oceanfish_medium_underwater_1=true,
battlestandard_damager=true, swordfishunderwater=true, mundy=true, oceanfish_medium_underwater_5=true, oceanfish_medium_underwater_2=true,
mutantshadowhive=true, oceanfish_small_underwater_1=true, suisei=true, totooria=true, shadowwinged=true, kemomimi_muou=true,
oceanfish_medium_underwater_8=true, grabbing_vinefixo=true, rneskeleton=true, lobster_land=true, oceanfish_small_underwater_5=true,
crocommander=true, pollenmiteden=true, oceanfish_small_underwater_2=true, oceanfish_medium_underwater_6=true, firetwister_seal=true,
mutantassassinbee=true, oceanfish_small_underwater_7=true, nightmarebeak_follower=true, oceanfish_medium_underwater_3=true,
rainbowjellyfish=true, oceanfish_small_underwater_3=true, oldfish_manypeople_player3=true, oceanfish_small_underwater_4=true,
wall_vl=true, snowperd=true, oceanfish_small_underwater_6=true, seatentacle=true, oceanfish_medium_underwater_7=true,
attacker_doll=true, suicong2=true, mutantdefenderbee=true, sandbag=true, oldfish_manypeople_player1=true, mecfish_alive=true,
ancient_trepidation=true, suicong=true, cherry_daylily=true, spiderb1=true, oceanfish_small_underwater_8=true,
goldfish_alive=true, bengbengbunny=true, medal_rage_krampus=true, stumpling=true, spiderb=true, swap_kaboom_hand=true,
girlfriend=true, squidunderwater2=true, megumin=true, kyno_redbarrel=true, cherryamulet=true, crawlingnightmare_follower=true,
change=true, lightninghound=true, spiderb2=true, xinlang=true, mothergoose=true, goose=true, legosi=true, scorpeon=true,
teruterubozu=true, pod=true, shadowpuddle=true, watame=true, turbina=true, kiara=true, pollenmites=true, woodpecker=true,
tentacleunderwater=true, boarilla=true, lala=true, sisters=true, wallace_bengbeng=true, phoenix=true, maple=true,
jy_pvz_crazydave=true, oldfish_manypeople_player4=true, wearger=true, shadow_teleporter=true, hollowknight=true,
daofeng=true, kyno_snowman=true, lizardman_tfc=true, jy_pvz_zombie=true, strange_scorpion_tfc=true, spiky_turtle_tfc=true,
cac=true, stepstool_stone=true, butterfly_spicy=true, devourer=true, piko_orange=true, jy_pvz_doublepeashooter=true,
tinyspider=true, joseph=true, jy_pvz_zombie_cone=true, birchling=true, eyeball=true, battlestandard_heal=true,
spiky_monkey_tfc=true, spider_drawing=true, pigman_drawing=true, wall_cookie=true, wolyo=true, clayhoundb=true,
firehoundb=true, lizardman_banner_tfc=true, kn=true, houndb=true, shadow_ly=true, wheeler=true, icehoundb=true,
kodi=true, roc_legp=true, forge_abigail=true, chimp=true, jy_pvz_nut=true, hoodedwidow=true, um_bear_trap=true,
old_shadowwaxwell=true, lostfight=true, bight=true, um_pawn=true, boxer=true, jy_pvz_snowpeashooter=true, jy_pvz_cattail=true,
jy_pvz_peashooter=true, jy_pvz_sunflower=true, jy_pvz_sunshroom=true, hatty_piggy_tfc=true, bishop_nightmareb=true,
knight_nightmareb=true, knightb=true, kelthuzad=true, bishopb=true, rneghost=true, miamirick=true, jy_pvz_cherrybomb=true,
zhuikong=true, kyno_jellyfish_rainbow=true, jy_pvz_magnetshroom=true, nana=true, rabbit_drawing=true, um_bear_trap_equippable_gold=true,
mermb=true, rimuru=true, mermb1=true, mermb2=true, calliope_mori=true, magmahound=true, maxwellboss=true, kuro=true,
red_lycoris_td1madao=true, xxx3=true, mock_dragonfly=true, spider_snow=true, jy_pvz_chomper=true, lily=true, reger=true,
babyspider=true, ergou=true, musichengyue=true, ylwarg=true, battlestandard_speed=true, jy_pvz_gatlingpeashooter=true,
wobysmall=true, kyno_pigelder=true, doghead=true, explosive_doll=true, piggolem=true, lostearth_gai=true, mindrake=true,
mutantrangerbee=true, jy_pvz_twinsunflower=true, shockworm=true, jy_pvz_zombie_imp=true, deerclopsboss=true, kopek=true,
jajangmon_ko_light_1=true, chester_hachi=true, ant_pet=true, jy_pvz_melon=true, wagstaff=true, toadling=true, jajangmon_ko_light_2=true,
jy_pvz_zombie_paper=true, beefalo_drawing=true, jy_pvz_zombie_yeti=true, lostfight_gai=true, sueshi=true, mothermossling=true,
wobybig=true, boat_moon=true, lilina=true, warg_boss=true, boarrior=true, apalala=true, rhinocebro=true, rhinodrill2=true,
forge_bernie=true, umaru_chan_td1madao=true, icelotus=true, cherry_beeguard=true, swilson=true, sporehound=true,
roship=true, knook=true, glacialhound=true, crystal_shield=true, otter=true, herald_crawlingnightmare=true, herald_nightmarebeak=true,
jy_pvz_zombie_jackbox=true, jy_pvz_wintermelon=true, rash=true, lostearth=true, vegeta=true, beeguard_dwx=true,
chungus=true, draven=true, musha_sandspike_med=true, lamb=true, kaichou=true, footballxd=true, ocsayaka=true, edelgard=true,
wirlywings=true, keine=true, giorno=true, krakenunderwater_tentacle=true, watermelon_lantern=true, merm_guard=true,
lavae2=true, personal_hutch=true, rockyblu=true, beequeen_dwx=true, oracle=true, kokoghost=true, tentaclep=true,
cherry_beequeen=true, jiusduelist=true, gw_ghost_hound=true, rhinocebro2=true, feather_cloud=true, sanae=true,
jy_pvz_variation_player_wilson=true, peachtreeguard=true, bossboarte=true, rorschach=true, boat_surfboard=true,
kangna=true, keg_l=true, conifer=true, ryn=true, lasthope_fisherman=true, lasthope_printskeeper=true, riven2_dst_td1madao=true,
lucia=true, platform_wood=true, tryndamere=true, lasthope_plantskeeper=true, klee=true, jajangmon_ko_light_3=true,
nightfoxy=true, boat_cant_move=true, lasthope_weaposnkeeper=true, lasthope_refineskeeper=true, jy_pvz_zombie_catapult=true,
kyno_shadowchanneler=true, hw_candle1=true, bossboar=true, scp035host=true, rocp=true, giyuu=true, plaguedoctor=true,
potato_oversized=true, mymoonbase=true, minotau=true, beetletaur=true, rhinodrill=true, ancient_trepidation_arm=true,
dust=true, daisy=true, wall_gothic=true, yorha2b_dst_td1madao=true, bronya_xd=true, jy_pvz_zombie_bucket=true,
jy_pvz_zombie_football=true, zhandou=true, lureplant_dwx=true, incineroar=true, lu=true, eyeplant_dwx=true, hasan_sabbah_td1madao=true,
dingo=true, swineclops=true, ringo=true, aip_dragon_tail=true, bronya=true, lucio=true, yuuki=true, inosuke=true,
guudebee=true, mutantshadowbee=true, sally=true, aip_dragon=true, kyno_pugna=true, jelliet=true, mandrakep=true,
jy_pvz_tallnut=true, wythe=true, antman_warrior_eggp=true, aku=true, thenose=true, dropperweb_craftable=true, summondrone=true,
rabbitwheel=true, bunnyman_snow=true, purpleguy=true, chocola=true, daxiong=true, crabking_clawp=true, kyno_biigfoot=true,
novakixx=true, leif_palm=true, shadow_dwx=true, servant=true, mushdrake_red=true, renwu=true, cherry_leif_spikes=true,
perd_super=true, simon=true, urara=true, wayne=true, wicker_tentacle=true, taizhen=true, tsumiki=true, kyno_shopkeeper2=true,
azzy=true, foxneel=true, skaily=true, flaire=true, kyno_shopkeeper1=true, grenade_holy=true, kyno_magmagolem=true,
kyno_pigking=true, slab_stone=true, ladder_wood=true, sealp=true, ganyu=true, dora=true, winifred=true, kyno_chicken=true,
kyno_snapdragon=true, merry=true, kyno_zeb=true, stepstool_wood=true, shion=true, beargerboss=true, kyno_pigking_elite=true,
slab_wood=true, platform_bouncepad=true, block_wood=true, oceanvine_cocoon_burnt=true, cadaver=true, makiri=true,
utsuho=true, gou=true, artorias=true, toga=true, tz_floating_music_shield_0=true, ratel=true, stoneman=true, deidara_dst_td1madao_explosive_clay_spider=true,
rockybluoriginal=true, eve=true, pugaliskp=true, fruitflylordp=true, ancient_robot_headp=true, ancient_hulkp=true,
balloonp=true, goddess_bird=true, archive_centipedep=true, battlestandard_shield_friendly=true, mad_ghost=true,
deer_redp=true, squidp=true, rookrepaired=true, bishoprepaired=true, fake_target_player=true, amelia=true, shadowmower=true,
xjj=true, shadow_knight2p=true, rengoku=true, owl=true, lty=true, lostumbrella=true, wort=true, max=true, dazai=true,
niko=true, zalekhalem=true, beatrice=true, battlestandard_shieldp=true, boaron_p=true, musha_sandspike_tall=true,
musha_sandspike_short=true, mandrakeman_bob=true, antman_warriorp=true, monkey_drawing=true, guudesuperbee=true,
shadow_rook2p=true, shadow_bishop2p=true, foxy=true, kyno_speartrap=true, parsee=true, moonmaw_dragonfly=true,
moonmaw_lavae=true, wolf=true, oracle_deer=true, tsui_balloon=true, kyno_royalguard_palace=true, um_pawn_nightmare=true,
spikewendy_tall=true, kyno_grub=true, kemomimi_npc_wx78=true, kemomimi_npc_wolfgang=true, kyno_sandbagsmall=true,
senjuro=true, satori=true, warbucks=true, manutsawee=true, heraldp=true, yehui=true, deerp=true, spidermonkeyp=true,
thunderbirdp=true, pangoldenp=true, toadstool_forest=true, papyrus_ghost=true, krownbig=true, kageminer=true, kageduelist=true,
lureplague_rat=true, kemomimi=true, spidermonkey2p=true, whimsy=true, peagawkp=true, gnarwail_attack_hornunderwater=true,
kemomimi_enemy=true, billp=true, kemomimi_npc_webber=true, trails=true, gnarwailp=true,

--2021/10
ghost_irritated=true, puppet=true, koma35p=true, xxx3_killerbutterfly=true, xxx3_eyeplant_3=true, ghost_clement=true,
mutantbarrack=true, zhongli=true, block_stone=true, warpspace=true, warpspacea=true, kemomimi_build_pig=true, medal_bee=true,
kemomimi_npc_warly=true, xxx3_eyeplant_4=true, xxx3_eyeplant_1=true, walrus_npc=true, little_walrus_npc=true, medal_beequeen=true,
medal_beeguard=true, eyeofterror=true, eyeofterror_mini_grounded=true, smile=true, kemomimi_npc_winona=true, eyeofterror_mini=true,
lux=true, xxx3_eyeplant_2=true, iexplorer=true, archive_centipede_huskp=true, peghook=true, shadowrabbit=true,
turtillus=true, medal_rose_terrace=true, gordon_ramsay=true, kemomimi_npc_wickerbottom=true, twinofterror1=true,
kemomimi_npc_kemomimi=true, twinofterror2=true, kemomimi_boss_dragon_bai=true, irys_hope=true, williambuster=true,
wall_cherryflower=true, battlestandard_damagerp=true, williambutler=true, jaye=true, kemomimi_npc_waxwell=true,
kemomimi_npc_wendy=true, williambutler_empty=true, williambrute=true, williambuster_empty=true, shirogane=true,
ghrazor=true, asakiri=true,

--2025/03
boat_pirate=true, hedgehound_bush=true, lightcrab=true, stageusher=true, daywalker=true, fence_junk=true, otterden=true,
boat_otterden=true, powder_monkey=true, boat_grass=true, warglet=true, lunarthrall_plant=true, punchingbag=true,
lunar_grazer=true, boat_bumper_kelp=true, boat_bumper_shell=true, punchingbag_shadow=true, punchingbag_lunar=true,
lunarthrall_plant_vine_end=true, cherry_watcher=true, boat_ice=true, boat_ancient=true, shadowprotector=true, ndnr_snake=true,
dragonboat_body=true, hedgehound=true, boat_bumper_crabking=true, shadowworker=true, nian_mount=true, polly_rogers=true,
prime_mate=true, ruins_shadeling=true, itemmimic_revealed=true, sharkboi=true, lilypad=true, icedpad=true, aip_cookiecutter_king=true,
viperworm=true, pigman_eskimo_shopkeep=true, lg_fishman=true, fused_shadeling=true, shadow_leech=true, ticoon=true,
gelblob=true, aip_oldone_spiderden=true, aip_oldone_marble=true, wall_dreadstone=true, ruinsnightmare=true, shadowthrall_horns=true,
shadowthrall_wings=true, aip_oldone_thestral=true, kyno_piko=true, kyno_piko_orange=true, crabking_mob=true, shadowthrall_hands=true,
kyno_chicken2=true, lg_balloon=true, daywalker2=true, barrel_gunpowder=true, cozy_bunnyman=true, mutatedbearger=true,
mutatedwarg=true, um_scorpion=true, aip_oldone_rabbit=true, mutateddeerclops=true, moonjelly=true, alpha_lightninggoat=true,
myth_nian=true, xd_jfsn=true, xd_qlch=true, boat_bumper_yotd=true, medal_naughty_krampus=true, crabking_cannontower=true,
fence_bamboo=true, wall_dwelling=true, mandrake_man=true, crabking_mob_knight=true, crabking_icewall=true, fence_gate_bamboo=true,
medal_spacetime_devourer=true, medal_spike_short=true, dragoon_qinglong=true, madameweb_spiderhome=true, medal_spike_med=true,
medal_spike_tall=true, medal_block=true, workingfly=true, acaoman=true, acaoguard=true, lg_butterfly=true, medal_dustmoth=true,
boat_ice_crabking=true, eyeofterror_mini_ally=true, lunarfrog=true, boatrace_seastack=true, lunarplanttentacle=true,
plant_nepenthes_l=true, e_bloodshield=true, rabbitking_aggressive=true, rabbitkingminion_bunnyman=true, madameweb_spider_warrior=true,
rabbitking_lucky=true, erd_soldier1=true, wx=true, mir=true, erd_schwyz=true, nymph=true, muelsyse_xin_muelsyse_copy=true,
mermguard_lunar=true, shadowdancer=true, erd_lavaslime=true, _dragonfly=true, cherrybug_purplebeetle=true, madameweb_pitfall_cocoon=true,
tropical_spider_warrior=true, madameweb_bee=true, cherrybug_greenbeetle=true, kyno_pebblecrab=true, chest_mimic_revealed=true,
_warglet=true, erd_lectbee=true, barrel_gunpowder_land=true, _warg=true, cherrybug_pearoachbeetle=true, yama_resurrectionstatue=true,
wall_scrap=true, erd_amelia=true, ndnr_mandrakeman=true, aip_score_ball=true, erd_rola=true, ali=true, fuelseeker=true,
colorful_deer=true, siving_foenix=true, wall_marble=true, daogui_chomper=true, daogui_colourfuldeer=true, xd_lightninggoat=true,
nervoustickden=true, madameweb=true, kyno_spiderhole=true, lg_boat=true, wonkey=true, moon_rabbit=true, siving_moenix=true,
nervoustick=true, nightcrawler=true, boat_woodlegs=true, aip_oldone_pot=true, xd_wukong_phantom=true, tentacle_abigail_williams=true,
raiden_shogun=true, mindweaver=true, pied_rat=true, shadowthrall_mouth=true, cherrybug_snailpink=true, lg_gongyang=true,
lg_muyang=true, kyno_adai_wargfant=true, legend_beeguard=true, siving_boss_flower=true, siving_egg=true, kyno_pigman_storeowner=true,
lg_nainiu=true, kyno_wildbore=true, tihu=true, dog_hound=true, pugalisk_3=true, dangkang=true, pugalisk_4=true,
dog_icehound=true, um_pyre_nettles=true, widow_web_combat=true, pugalisk_2=true, merm_shadow=true, genesis_fence=true,
wildchild=true, zhijiang_moonjellyfish=true, xd_qfwjdpuppet=true, mermprotector=true, wormwood_carrat=true, moyuxuanli=true,
yunmie=true, gestalt=true, aab_minion=true, cherrybomb=true, ndnr_nightmarebeak=true, wormwood_lightflier=true,
smallghost=true, killer_whale=true, erd_boar=true, xd_wukong_shadow=true, daogui_december18=true, uncompromising_packrat=true,
cherrybug_springada=true, shachong=true, cherrybug_butterflyautumn=true, kyno_adai_merm=true, kyno_adai_spider_monkey=true,
cherrybug_sneakada=true, kyno_chamaleon=true, daogui_crow=true, kyno_charlie_npc=true, aip_particles_entangled=true,
kyno_adai_pig_ghost=true, aip_dou_element_dawn_guard=true, um_beeguard_seeker=true, cherrybug_butterflyroyal=true,
cherrybug_mossquito=true, cherrybug_butterflyspring=true, daogui_dancing_lion=true, veigar=true, nilxin_null=true,
cherrybug_snailblue=true, lg_goldgod=true, mermguard_shadow=true, kyno_driftwood_fence=true, kyno_slurtlehole=true,
xd_koalefant=true, kyno_wargfant=true, buoy=true, viperling=true, kyno_pigman_florist=true, kyno_pigman_usher=true,
xd_beefalo=true, polarbear=true, polarfox=true, cherrybug_mothpink=true, aab_my_pig=true, kyno_wasphive=true, wall_polar=true,
um_beeguard_shooter=true, kyno_pigman_beautician=true, youmu=true, fsm_dangkang=true, diona=true, eirudy=true,
devotee=true, fsm_yunmie=true, fsm_ganmu=true, dielian_butterfly=true, aria_shadowservent=true, polar_penguin=true,
yama_commissioners=true, stu=true, cherrybug_goldbeetle=true, cherrybug_butterflywinter=true, rabbitking_passive=true,
gw_yellow_lizardman=true, cherrybug_fireneedle=true, cherrybug_butterflysummer=true, polarflea=true, xl_statue=true,
skd_monster1=true, ceres_fauna_treant=true, eyjafjalla_phonogragh=true, um_beeguard_blocker=true, mini_dreadeye=true,
worm_boss_dirt=true, lykz_tower=true, erd_treeelf=true, kyno_pigman_miner=true, kyno_pigman_erudite=true, wormwood_fruitdragon=true,
sgyy_minfang=true, sexycharlie_statue=true, sgyy_shaota=true, luciela=true, worm_boss=true, peterparrot=true, erd_rachel=true,
skd_monster2=true, xxx6_factory_stone=true, kyno_pigman_queen=true, rabbit_wcard_setpiece=true, sgyy_zhucheng=true,
cherrybug_ladybug=true, um_smolder_spore=true, dragonboat_shadowboat=true, skd=true, ndnr_crawlingnightmare=true,
warly_npc=true, chiikawa=true, kyno_tornadohazard=true, stanley=true, fsm_love_butterfly=true, pekora=true, sora_sign=true,
kyno_pigman_banker=true, krm_crawlingnightmare=true, erd_vernic=true, wilsondummy=true, fbk_shirakami=true, shachong_small=true,
venti=true, uruha_rushia_piyoko=true, krm_nightmarebeak=true, hlhy=true, kyno_pigman_hatmaker=true, waxwell_npc=true,
icey_carrook=true, webber_npc=true, xxx6=true, lambofthecult=true, xd_twinofterror1=true, boatrace_seastack_monkey=true,
lg_goldfly=true, hatkid=true, xd_soul_wolf=true, xd_twinofterror2=true, cooltarget=true, whitney=true, wilson_npc=true,
kyno_adai_ghost=true, aip_particles_echo=true, kyno_royalguard3=true, sora_fx_bird=true, wall_cherryruins=true,
sdf_chest_skull=true, erd_rockgolem1=true, jt_logfence=true, xd_swhs=true, wendy_npc=true, kyno_doydoy=true, um_bear_trap_equippable_tooth=true,
wes_npc=true, huangmozaichong=true, ifmgnrhtoidb_lxy_jpwhzh_lillqz=true, pyramidhead=true, frieren=true, mir2=true,
goldenglow=true, critter_eyeofterror=true, woodlegs_npc=true, kyno_royalguard1=true, kyno_pigman_collector=true,
fsm_baby_dangkang=true, breathlink=true, xd_sandblock=true, liuxingyanjiangchong=true, kyno_sugarfly=true, portableboat=true,
wolfgang_npc=true, wathgrithr_npc=true, wilba_npc=true, pekora_nousagi=true, a_dummytarget_chest=true, kyno_royalguard2=true,
tiddledoctor=true, pl_bat=true, kyno_pigman_hunter=true, kyno_pigman_farmer=true, suicong3=true, lg_firegod=true,
xd_dragonfly=true, mcw=true, wathom=true, shadow_charge=true, wickerbottom_npc=true, daogui_eyedevil=true, kyno_driftwood_gate=true,
slime=true, qyc_boarrior=true, walani_npc=true, eyeofterror_summon1=true, walter_npc=true, wagstaff_2_npc=true,
eyeofterror_summon2=true, wx78_npc=true, kyno_royalguard=true, spectator=true, kyno_monkeyisland_portal1=true,
sgyy_yellow_scarf1=true, sgyy_yellow_scarf2=true, cherrybug_grasscada=true, weisuo_cannon_turret=true, lg_fanglingche=true,
yaemiko=true, tf2scout=true, winona_npc=true, erd_lavarock=true, woodie_npc=true, lg_yisuerde=true, bh_firefly=true,
kokomi=true, mone_dummytarget=true, lostumbrella_gai=true, machinist=true, kyno_doydoy_baby=true, jalter=true,
kyno_pigman_mechanic=true, merm_lunar=true, aip_rubik_heart=true, monster_npc_walrus=true, erd_rockgolem2=true,
aip_rubik_ghost=true, tz_elong=true, xd_qlch_fs=true, ndnr_treeguard=true, wonkey_npc=true, monster_npc_little_walrus=true,
baby_dangkang=true, yeyu=true, shuoma_killerbee=true, xuaner=true, erd_musclee=true, ccs_butterfly=true, clara_doll_willful=true,
willow_npc=true, aab_polly_rogers=true, zhijiang_ancient_herald=true, archetto=true, jt_crossingfence=true, aip_oldone_sad=true,
kyno_pigman_mayor=true, sdf_asylum_grounds_barrier=true, sdf_wall_wood=true, sdf_wall_stone_pillar=true, eyjafjalla=true,
stalker_atriump=true, sdf_wall_hedge_decor=true, ccs=true, sdf_wall_stone=true, sdf_wall_hedge_block=true, kyno_pigman_professor=true,
krm_pet1=true, kyno_flytrap=true, xq_taoyao=true, aip_oldone_smile=true, kyno_royalguard4=true, kingslime=true,
uruha_rushia_fandead=true, hh_sharkboi=true, eyeofterror_mini_grounded_ally=true, leif_jungle=true, dio=true, air_conditioner_cloud=true,
firia=true, erd_rockgolem3=true, dishang_hutch=true, summonayami=true, wako=true, summonraiberuo=true, xhzq=true,
jotaro=true, elza=true, klein_goat=true, kotiya=true, xd_jcbird_spitter=true, wheeler_npc=true, kyno_monkeyisland_portal2=true,
xd_jcbird=true, elaina=true, lg_lilingyi=true, welina=true, ciyana=true, cherryruins_duck=true, surfboard=true,
skd_monster3=true, kuki=true, woodie_beaver_npc=true, kyno_wargfant_builder=true, crocommander_rapidfire=true,
mayoi=true, snapdragon_buddy=true, aip_eye_box=true, skd_monster4=true, wortox_decoy=true, wilba=true, monster_npc_bat=true,
cherryamuletfairy=true, wormla_vine=true, elena=true, foursixteen=true, xxx6_reaper=true, kyno_irongate=true, kyno_bishopboat=true,
ptribe_pigelitefighter4=true, ptribe_pigelitefighter3=true, ptribe_pigelitefighter1=true, ptribe_pigelitefighter2=true,
kyno_lobster=true, kyno_adai_parrot_witcher=true, kyno_knightboat=true, kyno_rookboat=true, munchkin=true, zhijiang_beeguard=true,
kyno_fishinhole=true, raph_balloon_mon=true, drspara=true, champion=true, e_hound=true, alice_pet1=true, yyxk_master=true,
wortox_npc=true, noise=true, tz_ecyballoonspeed=true, minotaur_organ=true, sgyy_zhucheng_2=true, kyno_adai_parrot=true,
aria_deathbutterfly1=true, imba_kiana_td1madao=true, aria_deathbutterfly2=true, nekosolly=true, alice_pet3=true,
aria_deathbutterfly3=true, yyxk_twister_seal=true, zhijiang_beeguard_sp=true, scorpionp=true, aip_particles_heart=true,
daogui_shadow_bishop=true, unika=true, zaolu=true, lc_bigbirdp=true, shamura_devil=true, atrium_overgrowth_zhijiang=true,
e_substitute4=true, wuyi_konnie=true, eog=true, genesis_boss_ladon_segment=true, wyley=true, lostchester_gai=true,
shambler=true, kemomimi_npc_sn=true, shanghai_doll=true, qingque=true, wormwood_npc=true, demogorgon=true, nanashi_mumei=true,
medal_shadowthrall_screamer=true, eog_minion=true, alice_pet4=true, gnatp=true,
xd_bearger=true, kyno_lunarrift_portal=true, ray_dilong=true, battlestandard_damager_friendly=true, snapperp=true,
alice_pet2=true, klein_squid=true, fourfive=true, zhijiang_nightmare_acao=true, xlperd=true, at_resurrectionstatue=true,
sgyy_minfang_2=true, yutu=true, fused_shadelingp=true, aip_tricky_thrower=true, player_hosted=true, tz_image=true,
cherrybug_mothwhite=true, yyxk_twister=true, trails2p=true, kuimu_alicia=true, xd_zhouwang=true, kuimu_cartesian=true,
at_phantom=true, bdrd=true, ptribe_wildbore=true, youling=true, aurora=true, kyno_whale_blue=true, chest_mimicp=true,
glacier=true, wurt_npc=true, syd=true, arakaluto=true, mercy=true, boaronp=true, antqueenp=true, riko=true, kemomimi_npc_willow=true,
pebblecrabp=true, fruitfly_goodp=true, destiny_miss_shadow=true, aip_oldone_jellyfish_stone=true, erd_dragon=true,
zhijiang_human=true, yyxk_pigelitefighter3=true, yeyu_shadowflower=true, tf2heavy=true, kkr=true, kyno_chicken_builder=true,
ayeyeplant=true, butterfly_moonp=true, futabasana=true, yyxk_pigelitefighter1=true, aip_particles_dusk=true, yyxk_pigelitefighter2=true,
cactusp=true, dragonfly_yulep=true, rena=true, daogui_twogods_ai=true, kyno_spidermonkey=true, cinnabunn=true,
erd_crevasse=true, mudrock_colosuss=true, malbatrossp=true, huimiezhe_tail=true, huimiezhe_body=true, pogp=true,
huimiezhe=true, mandrakemanp=true, battlestandard_speed_friendly=true, tr_butterfly=true, keqing=true, tr_lightqueen=true,
wes_clone=true, ouro_kronii=true, whisky=true, ptribe_pigman_royalguard=true, ptribe_pigbandit=true,
forge_woby=true, vampirebatp=true, goatmomp=true, kemomimi_npc_wes=true, kemomimi_npc_wathgrithr=true, chickenp=true,
pigelite_whitep=true, wueenbee=true, vagteouqivwx_yus_wmquwe_vahuvaxeb=true, pigelite_bluep=true, lostchester=true,
aip_oldone_wall=true, moonmothp=true, xxx2=true, zixiaxianzi_mythcharacter=true, shadowtentacle_player=true, abigail_clone=true,
sin=true, snake2p=true, babycatp=true, shadow3p=true, daogui_clone=true, boarriorp=true, tiddle_pigzombie=true,
kuimu_gestalt=true, e_energy=true, xd_spiderden=true, futabasana_windmill=true, dummytarget_shadow=true, monster_npc_pigman_farmer=true,
kyno_adai_mosquito=true, cotl_scampp=true, hermit=true, wonderwhy=true, dummytarget_lunar=true, spider_bh3=true,
q1bat=true, mutateddeerclopsp=true, lc_judgementbirdp=true, lc_apocbirdp=true, pm_duplighostp=true, wyrmmyrrh_boss=true,
merm_trader2p=true, cj_wolfgang=true, zg_mo_frog0=true, daidai=true, ccs_bee=true, aip_particles_morning=true,
yeyu_null=true, wanda_npc=true, hedgehound_bush=true, ikaros_dst_td1madao=true, neco=true, anan=true, cj_woodie=true,
aip_pet_mandrake_active=true, diana=true, aip_particles_night=true, lb_hound=true, wu_tao=true, zg_mo_goblin_robot_lightning=true,
battlestandard_healp=true, gilgamesh=true, daidai_swimring=true, elaina_evil_dragon=true, bulletbee=true, wundae=true,
dipperpines=true, giantgrubp=true, vagteouqivwx_yus_wmquwe_yccyhw=true, miranda=true, zskb_zombie=true, oceanhorror2hm=true,
bigfootp=true, shadowthrall_parasite=true, sharkp=true, kemomimi_npc_woodie=true, kyno_zeb_builder=true, spiderhome3=true,
kemomimi_npc_wilson=true, ushiwakamaru=true, brambletower=true, statue_jjh_maxwell=true, babygoose_yulep=true,
stalker_forestp=true, aip_slime_mold=true, strange_moonwall=true, adora=true, lc_censoredp=true, pidgeon2p=true,
kuimu_fldls=true, slipsp=true, kuimu_white=true, sona_etwahl_arcade=true, beefalo_f=true, lake_wolf=true, twab_tentacle_red=true,
stalkerp=true, yoyozi=true, twab_tentacle_blue=true, abbyp=true, fumop=true, citypig_malep=true, sjy_lingdie=true,
xd_zhouwang_shadow=true, goose_yulep=true, white_tiger=true, hound_mutantp=true, xhzqcloud=true, lz_minion=true,
aip_oldone_black_hand_stick=true, sayaka_surfboard=true, sayaka=true, otterp=true, aip_pet_rabbit=true, jungletreeguardp=true,
sheepp=true, huohuo=true, lc_punishingbirdp=true, veneto=true, shadowthrall_handsp=true, aip_sessho_seki=true,
mem_yue=true, mem_gjr=true, mem_wall=true, wall_hedge_block=true, stonefree_active=true, boykisser=true, lulu_bailuren=true,
tiddle_plaguerat=true, ptribe_pigman_royalguard_2=true, stonefree_big=true, erd_lecrhino=true, dungbeetlep=true,
fsm_ganmu_vine_end=true, mewkatp=true, tr_beeguard=true, lc_censoredbaby_npc=true, rainbowjellyfishp=true, jellyfishp=true,
goldship=true, elaina_magic_dragon=true, at_pet=true, kaki_broken=true, pigman_eskimo_shopkeep=true, barrel_gunpowder=true,
bronya_sc=true, wcard_shadowduelist=true, wcard_shadowdigger=true, wcard_shadowminer=true, wcard_shadowlumber=true,
chasni_spidermonkey=true, miamirick_nightmarebeak=true, bone_pet_black=true, clayvargp=true, wormla=true, chasni_ro_bin=true,
wolfspot=true, tvheadguy=true, hound_friend=true, bat_friend=true, hln_miner=true, sgyy_horse_black=true, sgyy_horse_normal=true,
sgyy_horse_white=true, flytrapp=true, goatkidp=true, fwd_in_pdt_animal_snake=true, miyi_snake=true, cookiecutterp=true,
nt_thunderbird=true, syd_pet=true, kyno_lunar_energy_wip=true, kyno_primeape=true, kyno_crabbit=true, tanya=true,
nilxin_shadowflower=true, wildboreguard=true, johnpaul2=true, cherryruins_gargoyle=true, powder_monkey=true,
boat_pirate=true, amnesia=true, haaton=true, matsuri_taiko=true, tees=true, nt_pig_ghost=true, centurion=true,
ump40=true, akizuki=true, breathlink_leif=true, lvbu=true, qiqi=true, mod_hardmode_lavae=true, greendeer_pet=true,
nt_biglavae=true, test=true, wall_hedge_layered_pink_aged=true, nt_werebeaver=true, punchingbag_chaos=true,
modifier_duelist=true, kyno_adai_zombee=true, ralsei=true, platform_carpet=true, yyxk_tigershark=true, battlestandard_heal_friendly=true,
afei=true, enderman=true, coda=true, gingerbread_pigp=true, kahiro=true, merm_trader1p=true, parrot2p=true, merm_guardp=true,
nilxin=true, spider_bh1=true, zskb_cedartree=true, spiderhome1=true, spider_bh2=true, spiderhome2=true, mikochi=true,
uruha_rushia=true, deerclops_yulep=true, xd_qypuppet=true, glowflyp=true, daogui_blm=true, wharang_miho=true, gorge_swamppig=true,
spider_moonp=true, pebblecrab=true, darkshadow=true, rxg=true, sflan=true, zombie_brainless=true, overlord_ainz=true,
shadowwarfarin=true, fruitdragonp=true, trailsp=true, grotto_grub=true, rei_dummytarget=true, zhizunbao_mythcharacter=true,
golemp=true, hippop=true, zombie_blue=true, xxx_shuoma=true, wark=true, frisia=true, zhangyu=true, zombie_red=true,
zombie_grey=true, kyno_lunar_energy=true, cherrift_beehive=true, cherrift_bee=true, wixie_shadow_clone=true, shadow_wixie=true,
kyno_adai_herald=true, aki=true, mutatedbeargerp=true, daywalkerp=true, alterguardianp=true, esentryy=true, toadstool_darkp=true,

}



--No add of health_info
BLACK_FILTER = {
boat_item=true, boat_item_collision=true, boat_player_collision=true, 
carrat_planted=true, deer_growantler_fx=true, deer_unshackle_fx=true, eyeturret_base=true, hutch_music_light_fx=true, 
minotaurchestspawner=true, shadow_bishop_fx=true, 

world=true, forest=true, cave=true, shard_network=true, world_network=true, cave_network=true, maxwellthrone=true, maxwelllight=true, yellowstaff=true, trinket_8=true, armorruins=true, wall_wood_item=true, puppet_wickerbottom=true, monsterlasagna=true, tophat=true, beefalohat=true, stick=true, firepit_placer=true, cave_banana_tree=true, teleportato_box=true, wardrobe_blueprint=true, turf_carpetfloor=true, boomerang=true, smallhumanmeat_dried=true, plant_normal=true, turf_carpetfloor_blueprint=true, science_blueprint=true, rock_moon=true, turf_savanna=true, beargerwarning_lvl2=true, minifan=true, spidereggsack_placer=true, ratatouille=true, animal_track=true, wall_stone_item_blueprint=true, blueamulet_blueprint=true, stalagmite=true, cookpot=true, pitchfork_blueprint=true, yellow_leaves_chop=true, brokenwall_ruins=true, icepack_blueprint=true, waxwelljournal=true, taffy=true, arrowsign_panel_placer=true, orangeamulet_blueprint=true, walrus_tusk=true, werebeaver_transform_fx=true, sewing_kit=true, golden_tooth=true, chessjunk3=true, gunpowder=true, sounddebugicon=true, humanmeat=true,
teleportato_base=true, amulet_blueprint=true, beemine_maxwell=true, lureplantbulb_placer=true, minerhat=true, trunkvest_summer_blueprint=true, bandage_blueprint=true, reticule=true, purple_leaves=true, collapse_big=true, lightning_rod_placer=true, rock_flintless_med=true, deerclops_eyeball=true, pillar_cave_flintless=true, spawn_fx_tiny=true, pond_cave=true, light_blueprint=true, wormlight_light_fx_lesser=true, evergreen_sparse_normal=true, armorslurper_blueprint=true, spawn_fx_small=true, cane_blueprint=true, honeyham=true, orangegem=true, treasurechest_blueprint=true, amulet=true, ruinshat=true, dragonflychest=true, upper_nightmarefissurefx=true, torch=true, wormlight=true, krampuswarning_lvl3=true, siestahut=true,
spat_splash_fx_low=true, mining_fx=true, birdcage_blueprint=true, marble=true, evergreen_stump=true, wormlight_lesser=true, pond_algae=true, durian=true, spidereggsack=true, firestaff_blueprint=true, deciduous_root=true, dug_grass_placer=true, waterballoon=true, flower_withered=true, featherhat_blueprint=true, wardrobe=true, researchlab_placer=true, icehat_blueprint=true, telebase_blueprint=true, ice=true, attackfire_fx=true, lavae_egg=true, marbletree_2=true, spider_web_spit=true, farmrock=true, spat_splash_fx_full=true, honey=true, bonestew=true, molehat=true, brokenwall_stone=true, cactus_flower=true, human_amulet=true, trinket_13=true, cave_banana=true, wormwarning_lvl3=true, campfire_placer=true, deerclopswarning_lvl2=true, treasurechest=true, cave_exit=true, bearger_fur=true, watermelonicle=true, moose_nest_fx_idle=true, foliage=true, 
heatrocklight=true, hawaiianshirt_blueprint=true, trinket_25=true, cave_banana_stump=true, staff_tornado=true, arrowsign_post_placer=true, icepack=true, pottedfern_blueprint=true, wall_moonrock_item_blueprint=true, siestahut_placer=true, depleted_grass=true, butterfly_placer=true, book_birds_blueprint=true, pigskin=true, lavae_move_fx=true, homesign=true, bishop_charge_hit=true, onemanband=true, cookedmonstermeat=true, dug_berrybush2=true, trinket_11=true, dr_warmer_loop=true, cookedmeat=true, trunk_summer=true, trap_teeth_placer=true, slurtlehat=true, homesign_blueprint=true, healingsalve=true, signright=true, cutstone_blueprint=true, teamleader=true, mushtree_small_stump=true, evergreen_short=true, beargervest_blueprint=true, mushtree_tall_bloom_burntfx=true, razor_blueprint=true, turf_woodfloor_blueprint=true, beefalohat_blueprint=true, spidereggsack_blueprint=true, firepit_blueprint=true, cavelight_small=true, icestaff_blueprint=true, lightning_rod_fx=true, blowdart_sleep=true, 
batbat_blueprint=true, cave_entrance_ruins=true, ruins_bat=true, pottedfern=true, impact=true, slow_farmplot=true, cave_banana_cooked=true, blueamulet=true, lighterfire=true, lightbulb=true, turf_deciduous=true, heatrock=true, attune_in_fx=true, butterflywings=true, red_cap_cooked=true, pine_needles_chop=true, splash_snow_fx=true, coldfirepit=true, maxwelllight_area=true, krampus_sack=true, earmuffshat=true, wall_hay_item_blueprint=true, trinket_18=true, greenamulet_blueprint=true, treasurechest_placer=true, flowerhat_blueprint=true, eggplant=true, ground_blood=true, fire_projectile=true, vomitfire_fx=true, groundpoundring_fx=true, eel_cooked=true, footballhat=true, lightning_rod=true, turf_cave=true, spawnlight_multiplayer=true, rubble=true, boards_blueprint=true, tallbirdegg=true, eye_charge=true, evergreen_sparse_short=true, human_amulet_blueprint=true, beemine_placer=true, mushtree_small_bloom_burntfx=true, monkeyprojectile=true, evergreen_burnt=true, lavae_egg_cracked=true, fishingrod_blueprint=true, chessjunk1=true, dr_warm_loop_2=true, icehat=true, spear_blueprint=true, powcake=true, human_vest_blueprint=true, 
frontend=true, telebase=true, pigtorch_flame=true, beefalowool=true, tallbirdegg_cracked=true, trunk_cooked=true, rabbithouse=true, charcoal=true, stalagmite_tall=true, armordragonfly_blueprint=true, researchlab3_placer=true, beemine_blueprint=true, houndwarning_lvl1=true, wormlight_light_lesser=true, blue_cap_cooked=true, bird_egg=true, mushtree_small=true, baconeggs=true, book_sleep=true, emote_fx=true, puppet_wes=true, glommerwings=true, coldfire=true, acorn_sapling=true, trinket_15=true, cutreeds=true, coldfirepit_placer=true, ruins_bat_blueprint=true, drumstick=true, purple_leaves_chop=true, cookedsmallmeat=true, eyeturret_item_blueprint=true, coldfirepit_blueprint=true, batwing_cooked=true, goldenshovel=true, armorslurper=true, furtuft=true, mist=true, pomegranate_cooked=true, meatrack_placer=true, beebox=true, raindrop=true, lanternlight=true, beardhair=true, pickaxe_blueprint=true, eyebrellahat_blueprint=true, plantmeat_cooked=true, hawaiianshirt=true, abigail_flower_blueprint=true, spore_medium=true, deerclopswarning_lvl4=true, panflute_blueprint=true, lightning=true, deciduoustree_burnt=true, 
minotaurchest=true, mermhead_blueprint=true, wall_wood_item_blueprint=true, icespike_fx_1=true, nightsword_blueprint=true, snowball=true, mossling_spin_fx=true, trap_teeth=true, birdcage_placer=true, war_blueprint=true, burntstickleft=true, town_blueprint=true, turf_checkerfloor_blueprint=true, researchlab3_blueprint=true, nightmare_timepiece_blueprint=true, tools_blueprint=true, cookpot_placer=true, mushtree_tall_webbed=true, waxwell_book_fx=true, greenamulet=true, feather_crow=true, mushtree_tall_webbed_burntfx=true, balloons_empty=true, drumstick_cooked=true, dug_berrybush2_placer=true, groundpound_fx=true, stalagmite_tall_med=true, catcoonhat_blueprint=true, smallmeat_dried=true, staffcastfx_mount=true, rubble_low=true, tallbirdegg_cooked=true, yellowamulet=true, beefalo_transform_fx=true, character_fire=true, red_leaves_chop=true, honeycomb=true, blowdart_sleep_blueprint=true, fissure_lower=true, firesuppressor=true, flower_cave_double=true, firesuppressor_placer=true, wathgrithr_spirit=true, spiderhole_rock=true, adventure_portal=true, mooseegg=true, silk=true, turf_rocky=true, book_brimstone_blueprint=true, 
lightning_rod_blueprint=true, goldenshovel_blueprint=true, bedroll_furry_blueprint=true, book_brimstone=true, researchlab4_blueprint=true, balloons_empty_blueprint=true, cavelight=true, houndstooth=true, siestahut_blueprint=true, petals=true, splash_ocean=true, evergreen_tall=true, container_classified=true, armor_sanity=true, houndwarning_lvl4=true, bugnet=true, blowdart_fire=true, turf_road=true, meatballs=true, eggplant_cooked=true, thulecite_blueprint=true, trinket_4=true, goldenpickaxe=true, catcoonhat=true, firering_fx=true, bernie_inactive=true, piggyback=true, staff_tornado_blueprint=true, humanmeat_cooked=true, compass=true, ruins_statue_head=true, umbrella_blueprint=true, acorn_cooked=true, diviningrodbase=true, chessjunk2=true, goatmilk=true, tent_blueprint=true, cutlichen=true, lumpy_sapling=true, winterhat=true, mosquitosack=true, green_leaves=true, mushtree_tall_stump=true, rope=true, strawhat_blueprint=true, fire=true, fast_farmplot=true, pillar_cave=true, wardrobe_placer=true, petals_evil=true, wormwarning_lvl4=true, icespike_fx_2=true, turf_marsh=true, dug_berrybush=true, arrowsign_post=true, shatter=true, featherfan_blueprint=true, jammypreserves=true, pumpkin_cooked=true, beehat=true, spawn_fx_medium=true, footballhat_blueprint=true, 
telebase_placer=true, turf_fungus_red=true, dug_marsh_bush_placer=true, nightstickfire=true, butter=true, wall_ruins_item_blueprint=true, poopcloud=true, fencepost=true, fast_farmplot_placer=true, lifeinjector_blueprint=true, earmuffshat_blueprint=true, umbrella=true, winterometer=true, pillar_stalactite=true, winterometer_blueprint=true, puppet_wilson=true, watermelonhat=true, waffles=true, batcave=true, hotchili=true, plantmeat=true, grass_umbrella=true, backpack=true, explode_small_slurtlehole=true, cookpot_blueprint=true, marbletree=true, dug_sapling_placer=true, maxwell_smoke=true, mushtree_tall=true, deerclopswarning_lvl1=true, green_leaves_chop=true, penguin_ice=true, slurtle_shellpieces=true, tauntfire_fx=true, slow_farmplot_blueprint=true, dr_hot_loop=true, armorruins_blueprint=true, gridplacer=true, maxwelllock=true, frostbreath=true, wall_stone_item=true, winterometer_placer=true, rainhat_blueprint=true, firepit=true, marbletree_3=true, purplegem=true, bugnet_blueprint=true, flowersalad=true, trinket_24=true, mushtree_medium_stump=true, wall_ruins_item=true, berrybush2=true, puppet_woodie=true, molehat_blueprint=true, yellowamulet_blueprint=true, lifeinjector=true, bedroll_furry=true, shadowmeteor=true, puppet_wathgrithr=true, froglegs_cooked=true, 
blowdart_pipe_blueprint=true, puppet_wx78=true, nightmarelight=true, puppet_webber=true, watermelon=true, watermelonhat_blueprint=true, coldfire_blueprint=true, maxwelllight_flame=true, flower_cave=true, carrot=true, dragonfruit_cooked=true, razor=true, turkeydinner=true, fishsticks=true, meatrack_blueprint=true, book_tentacles=true, ash=true, axe_blueprint=true, papyrus=true, brokenwall_wood=true, rainometer_blueprint=true, turf_fungus=true, yellowstaff_blueprint=true, shadowhand=true, sweatervest_blueprint=true, firesuppressor_blueprint=true, arrowsign_panel=true, resurrectionstatue=true, lavalight=true, turf_dragonfly=true, icebox_blueprint=true, bedroll_straw_blueprint=true, trinket_10=true, farmrocktall=true, mushtree_medium_bloom_burntfx=true, book_birds=true, walrushat=true, marbletree_4=true, armormarble=true, magic_blueprint=true, human_ribs=true, dragonflychest_placer=true, turf_fungus_green=true, researchlab2=true, lava_pond_rock6=true, researchlab2_placer=true, monkeybarrel=true, cave_entrance_open=true, pumpkincookie=true, fishtacos=true, stalagmite_med=true, armormarble_blueprint=true, seeds_cooked=true, froglegs=true, forcefieldfx=true, skullchest=true, pigtorch_fuel=true, fertilizer_blueprint=true, puppet_wolfgang=true, rope_blueprint=true, carrot_cooked=true, mandrake=true, saddle_war_blueprint=true, eel=true, researchlab4=true, researchlab_blueprint=true, feather_robin=true, tent_placer=true, 
deciduoustree_short=true, trinket_21=true, cavelight_tiny=true, acorn=true, heatrock_blueprint=true, minerhat_blueprint=true, moonrocknugget=true, rainhat=true, marbletree_1=true, mushtree_medium_burntfx=true, hammer=true, cookedmandrake=true, stickleft=true, turf_dragonfly_blueprint=true, armorgrass_blueprint=true, nightmarefuel=true, fan_wheel=true, axe=true, reviver_blueprint=true, yellowgem=true, monstermeat_dried=true, bluegem=true, human_vest=true, book_fx=true, greenstaff=true, minerhatlight=true, humanmeat_dried=true, featherfan=true, armorwood_blueprint=true, spear_wathgrithr=true, trinket_9=true, eyeturret_item=true, smoke_plant=true, gears=true, mushtree_tall_burntfx=true, bearger_fur_blueprint=true, lucy_classified=true, attune_ghost_in_fx=true, flowerhat=true, birdtrap_blueprint=true, pinecone=true, beemine=true, durian_seeds=true, gunpowder_blueprint=true, fish=true, greenstaff_blueprint=true, honeynuggets=true, saddle_war=true, grass_umbrella_blueprint=true, tentaclespots=true, tentaclespike=true, teleportato_potato=true, tentacle_pillar_hole=true, trinket_14=true, fruitmedley=true, turf_forest=true, tears=true, dragonfruit=true, orangestaff_blueprint=true, rock_light=true, frogglebunwich=true, horn=true, deciduoustree_tall=true, teleportato_ring=true, 
gemsocket=true, healingsalve_blueprint=true, diviningrodstart=true, diviningrod=true, goldenaxe=true, bushhat_blueprint=true, maxwellphonograph=true, trinket_3=true, nightmarelightfx=true, pighouse_placer=true, cactus_meat=true, redgem=true, rottenegg=true, wathgrithrhat=true, bedroll_straw=true, rainometer=true, resurrectionstatue_blueprint=true, coldfire_placer=true, writeable_classified=true, nightsword=true, dragonpie=true, burntfencepostright=true, rainometer_placer=true, spat_splash_fx_melted=true, homesign_placer=true, berries=true, raincoat=true, firesplash_fx=true, lucy_transform_fx=true, glommerflower=true, hambat_blueprint=true, turf_desertdirt=true, fencepostright=true, book_sleep_blueprint=true, stickright=true, dragon_scales=true, nightstick_blueprint=true, sewing_kit_blueprint=true, pumpkin_seeds=true, krampuswarning_lvl1=true, die_fx=true, goldenpickaxe_blueprint=true, birdtrap=true, staff_castinglight=true, spat_bomb=true, ice_projectile=true, sanity_lower=true, puppet_willow=true, meat_dried=true, book_fx_mount=true, phlegm=true, small_puff=true, lightninggoathorn=true, thunder_far=true, book_gardening_blueprint=true, 
trinket_7=true, trinket_20=true, stafflight=true, stuffedeggplant=true, livinglog=true, monstermeat=true, slow_farmplot_placer=true, stalagmite_full=true, beargerwarning_lvl3=true, explode_small=true, brokenwall_moonrock=true, krampuswarning_lvl2=true, nightstick=true, ancient_altar_broken=true, green_cap_cooked=true, whip_blueprint=true, blowdart_walrus=true, piggyback_blueprint=true, stalagmite_low=true, wathgrithrhat_blueprint=true, stalagmite_tall_full=true, tumbleweedbreakfx=true, rabbithouse_placer=true, fertilizer=true, meatrack=true, lureplantbulb=true, fish_cooked=true, burntfencepost=true, shadowwatcher=true, icecream=true, spear_wathgrithr_blueprint=true, pighead_blueprint=true, pillar_cave_rock=true, mandrake_planted=true, reflectivevest_blueprint=true, statueharp=true, nightmarefuel_blueprint=true, lucy_ground_transform_fx=true, boneshard=true, ruins_statue_head_nogem=true, moose_nest_fx_hit=true, shadowhand_arm=true, ruins_statue_mage=true, reviver=true, fissure=true, trinket_5=true, 
fast_farmplot_blueprint=true, guacamole=true, orange_leaves_chop=true, corn=true, brokenwall_hay=true, lighter=true, turf_dirt=true, puppet_wendy=true, wetgoop=true, ground_chunks_breaking=true, steelwool=true, mermhead=true, spat_splat_fx=true, collapse_small=true, greengem=true, sweatervest=true, orangestaff=true, firesuppressor_glow=true, icebox_placer=true, trunkvest_winter_blueprint=true, chester_transform_fx=true, blowdart_fire_blueprint=true, shovel_dirt=true, minotaurhorn=true, trunkvest_winter=true, lucy=true, coldfirefire=true, trinket_23=true, splash_spiderweb=true, trinket_22=true, lighter_blueprint=true, bandage=true, wall_hay_item=true, blue_cap=true, mole_move_fx=true, tallbirdnest=true, researchlab2_blueprint=true, dragonfruit_seeds=true, mushtree_small_burntfx=true, mandrakesoup=true, teleportato_crank=true, icebox=true, tent=true, batbat=true, winterhat_blueprint=true, dragonflychest_blueprint=true, manrabbit_tail=true, pandoraschest=true, beehat_blueprint=true, 
wall_stone_item_placer=true, trinket_17=true, thulecite_pieces=true, torchfire=true, transistor=true, tophat_blueprint=true, dress_blueprint=true, lantern_blueprint=true, trap=true, purpleamulet=true, guano=true, book_tentacles_blueprint=true, spiderhat=true, burntstick=true, researchlab3=true, nightlight_blueprint=true, trinket_2=true, telestaff=true, boomerang_blueprint=true, trinket_6=true, staffcastfx=true, slurtleslime=true, perogies=true, thulecite=true, trunkvest_summer=true, rock_flintless_low=true, statue_transition_2=true, houndwarning_lvl3=true, thunder_close=true, 
trinket_26=true, signleft=true, hammer_blueprint=true, smallhumanmeat=true, feather_robin_winter=true, birdcage=true, trunk_winter=true, book_gardening=true, purplegem_blueprint=true, durian_cooked=true, pinecone_placer=true, watermelon_seeds=true, turf_grass=true, turf_woodfloor=true, onemanband_blueprint=true, armor_sanity_blueprint=true, turf_checkerfloor=true, icespike_fx_3=true, nightmarefissurefx=true, turf_underrock=true, unagi=true, turf_mud=true, reflectivevest=true, orangeamulet=true, eye_charge_hit=true, ruins_statue_mage_nogem=true, rabbithouse_blueprint=true, survival_blueprint=true, corn_cooked=true, pomegranate=true, pomegranate_seeds=true, attune_out_fx=true, sparks=true, trap_teeth_blueprint=true, 
carrot_seeds=true, evergreen_sparse_tall=true, farmrockflat=true, coontail=true, pumpkin_lantern_blueprint=true, watermelon_cooked=true, berries_cooked=true, smallmeat=true, goldenaxe_blueprint=true, eggplant_seeds=true, lantern=true, bird_egg_cooked=true, wall_wood_item_placer=true, wall_hay_item_placer=true, icespike_fx_4=true, explode_small_slurtle=true, slurperlight=true, burntstickright=true, wall_ruins_item_placer=true, trailmix=true, wall_moonrock_item_placer=true, turf_sinkhole=true, sanity_raise=true, wormlight_light=true, red_cap=true, warningshadow=true, whip=true, turf_road_blueprint=true, telestaff_blueprint=true, mushtree_medium=true, arrowsign_post_blueprint=true, torch_blueprint=true, 
deciduoustree_normal=true, wormlight_light_fx=true, wormlight_plant=true, wormwarning_lvl2=true, green_cap=true, shovel_blueprint=true, refine_blueprint=true, pighouse_blueprint=true, smallhumanmeat_cooked=true, human_eye_bloody=true, human_eye_dried=true, rockyherd=true, scalp=true, bernie_inactive_blueprint=true, human_spine=true, human_skull=true, houndfire=true, deciduoustree_stump=true, blowdart_pipe=true, beebox_blueprint=true, beebox_placer=true, farm_blueprint=true, hud=true, saddle_basic_blueprint=true, brokentool=true, trinket_16=true, stalagmite_tall_low=true, penguinherd=true, multitool_axe_pickaxe_blueprint=true, tornado=true, eyeturret_item_placer=true, lichen=true, pillar_algae=true, 
purpleamulet_blueprint=true, chesterlight=true, cave_banana_burnt=true, pillar_ruins=true, campfire=true, nightlight=true, hambat=true, meat=true, minifan_blueprint=true, wormhole_limited_1=true, dug_berrybush_placer=true, flower_cave_triple=true, dug_marsh_bush=true, ancient_blueprint=true, slurper_pelt=true, goose_feather=true, armorsnurtleshell=true, spore_small=true, acorn_placer=true, trinket_1=true, bishop_charge=true, deerclopswarning_lvl3=true, butterflymuffin=true, pottedfern_placer=true, ghost_transform_overlay_fx=true, rubble_med=true, statue_transition=true, trinket_19=true, ruinshat_blueprint=true, firestaff=true, spidergland=true, waterballoon_blueprint=true, eyebrellahat=true, waterballoon_splash=true, diviningrod_blueprint=true, spider_web_spit_creep=true, wormwarning_lvl1=true, transistor_blueprint=true, corn_seeds=true, splash=true, 
trap_blueprint=true, nightlight_placer=true, blueprint=true, compass_blueprint=true, ancient_altar=true, papyrus_blueprint=true, wall_moonrock_item=true, fishingrod=true, meteorwarning=true, nightlight_flame=true, migration_portal=true, marblepillar=true, trap_teeth_maxwell=true, spear=true, campfire_blueprint=true, pumpkin=true, beargerwarning_lvl4=true, resurrectionstatue_placer=true, bushhat=true, beargervest=true, hauntfx=true, backpack_blueprint=true, basalt=true, lavae_tooth=true, abigail_flower=true, trinket_12=true, armordragonfly=true, multitool_axe_pickaxe=true, basalt_pillar=true, campfirefire=true, kabobs=true, spat_splash_fx_med=true, beargerwarning_lvl1=true, dr_warm_loop_1=true, batwing=true, maxwell=true, saddle_basic=true, evergreen_normal=true, nitre=true, researchlab=true, raincoat_blueprint=true, cactus_meat_cooked=true, spore_tall=true, 
shock_fx=true, researchlab4_placer=true, nightmare_timepiece=true, cane=true, caverain=true, cave_fern=true, attunable_classified=true, trinket_27=true, houndwarning_lvl2=true, }


